### ISSUE TITLE
그림판 만들기

### ISSUE THREAD

**Issue by seacrab808** [LeHiHo/FastMind#11]
## 목적
그림판 컴포넌트 canvas api로 만들기

## 세부 내용
게임방 내부에 있는 주요 기능으로, 그림판 컴포넌트를 제작한다. 
데스크탑 모드에서 마우스로 그릴 수 있는 로직으로, 색, 굵기 변경 및 지우개 기능이 있다. 

## TODO-List
- [x] 캔버스 안에 마우스로 그림 그릴 수 있게 구현하기
- [x] 색 변경하는 버튼 만들기
- [x] 굵기 변경하는 바 만들기
- [x] 지우기 기능 만들기
- [x] 전체 지우는 기능 만들기
