### ISSUE TITLE
대기방 UI 구현

### ISSUE THREAD

**Issue by Sinary00** [LeHiHo/FastMind#18]
## 목적
대기방(로비) UI 구현

## 세부 내용
- 대기방 UI 구현
- 페이지 네이션 구현
- 스크롤바 커스텀
- 방 번호 로직
- 최신순 정렬
- 1:1채팅 이전대화불러오기 에러 수정
- 1:1채팅 실시간채팅 불러오기 중복 에러수정

## TODO-List
- [x] 대기방 UI 구현
- [x] 페이지 네이션 구현
- [x] 스크롤바 커스텀
- [x] 방 번호 로직
- [x] 최신순 정렬
- [x] 1:1채팅 이전대화불러오기 에러 수정
- [x] 1:1채팅 실시간채팅 불러오기 중복 에러수정
