### ISSUE TITLE
채팅기능 구현

### ISSUE THREAD

**Issue by Sinary00** [LeHiHo/FastMind#19]
## 목적
대기방(로비) 및 게임방 채팅 기능 구현

## 세부 내용
- socket.io를 이용하여 실시간 채팅 기능 구현
-  isPrivate: true 1:1 채팅 /  isPrivate: false 게임방 채팅 구분 로직 추가
- 나의 채팅 조회 api 연동 후 isPrivate: true인 채팅방만 반환하는 로직 추가 (1:1대화 리스트)
- 1:1채팅 유저 온라인 오프라인 여부 구분 로직 추가 (1:1대화 리스트)
- 채팅 시간에 따른 메세지 분리 로직 추가
- 채팅 메세지 중 본인이 친 메세지 구분 로직 추가
- chatId에따른 모달창 분리 기능

## TODO-List
- [x] chatId값에 해당하는 지난 채팅 기록 불러오기
- [x] 실시간 서버 전송되는 채팅 데이터 받아오기
- [x] 서버에 채팅 메세지 보내기
- [x] 나의 채팅 조회 api 연동, isPrivate: true인 채팅방만 반환
- [x] 나의 유저 데이터 반환
- [x] 1:1채팅 유저 온라인 오프라인 여부 구분
- [x] 채팅 시간에 따른 메세지 분리
- [x] 채팅 메세지 중 본인이 친 메세지 구분
- [x] date 구조 변환 및 날짜/시간  분리
- [x] 채팅 메세지 date 정렬 순서 최근 역순 변경
- [x] (1:1대화) 1:1대화 리스트 패치 구현
- [x] (1:1대화) 나의 유저데이터와 비교 후 나를 제외한 유저만 1:1 대화 리스트에 출력
- [x] chatId에따른 모달창 분리
