### ISSUE TITLE
소켓 연결 에러 수정

### ISSUE THREAD

**Issue by Sinary00** [LeHiHo/FastMind#30]
## 목적
소켓 연결 에러 수정 및 공통 컴포넌트 화

## 세부 내용
- allList 무한 렌더링 해결
- 게임룸 무한 렌더링 해결
- allList와 onlineList name->id로 비교 
- 공통된 useEffect부분 공통 컴포넌트 화

## TODO-List
- [x] allList 무한 렌더링 해결
- [x] 게임룸 무한 렌더링 해결
- [x] allList와 onlineList name->id로 비교 
- [x] 공통된 useEffect부분 공통 컴포넌트 화
