### ISSUE TITLE
그림판 소켓 연결

### ISSUE THREAD

**Issue by seacrab808** [LeHiHo/FastMind#33]
## 목적
그림판 소켓 연결을 하려고 합니다

## 세부 내용
drawing.tsx에 소켓 관련 코드 추가

## TODO-List
- [x] 소켓 관련 코드 추가
- [ ] 백엔드 코드 요청 -> 실패 ^^
- [x] 백엔드 로직 구현 / 배포 
- [x] 배포 후 연결
