### ISSUE TITLE
게임방 생성, 온라인/오프라인 유저 확인, 모든 게임방 조회

### ISSUE THREAD

**Issue by yangjaehyuk** [LeHiHo/FastMind#4]
## 목적
 - 로비 내에서 게임방 생성
 - 로그인 시 lobby로 소켓 연결
 - 로비 내에서 온라인/오프라인 유저 리스트로 보여주기
 - 유저 마다 생성된 모든 게임방 리스트로 보여주기 

## 세부 내용
 - socket.io 이용하여 end point인 lobby로 연결
 - 파라미터는 로그인 할 때 사용한 id값
 - id값은 모두가 다 다르므로 개개인 별 구분 가능
## TODO-List
- [ ] 게임 방 생성
- [ ] 로그인 시 소켓 연결
- [ ] 로비 내 온라인/오프라인 유저 보여주기
- [ ] 게임방 리스트 보여주기
