### ISSUE TITLE
채팅방 내 모든 유저의 name, picture, id 값을 반환하는 로직 공통화 구현, 방 나가기, 방 초대하기, 게임방 실시간 채팅

### ISSUE THREAD

**Issue by yangjaehyuk** [LeHiHo/FastMind#45]
## 목적
 - 채팅방 기능 활성화
 - 채팅방 ui 개선
 - 방 나가기 시 leave 써서 다시 데이터 받고 뿌려주기
 - 게임 방에 들어갔을 때 다른 게임방 못 들어가는 로직 작성
## 세부 내용
 - 방 나갈 때 chatId 소켓 disconnect
 - 초대할 때 onlineUserList와 방 내 onlineUserList 비교한 후 공통된 부분이랑 채팅방 내 들어가 있는 userId 비교 후 로직 작성
 - 유저 구분을 위한 채팅방 내 유저아이디, 사진, 닉네임 띄워주기
## TODO-List
- [x] 방 나가기
- [ ] 방 초대하기
- [x] 실시간 채팅
- [x] 채팅방 내 모든 유저의 name, picture, id값 반환 로직 공통화
- [x] 0명 시 방 삭제 로직 구현
- [x] 0명 방 진입 하려할 때 에러 뜨면 alert으로 막기
