### ISSUE TITLE
1:1 채팅방 만들기 및 초대하기 기능

### ISSUE THREAD

**Issue by gkdus2217** [LeHiHo/FastMind#49]
## 목적
1:1 채팅방 만들기 및 초대하기 기능 구현

## 세부 내용
- 1:1 채팅방 만들기 모달 구현
- 유저 검색 기능
- 검색한 유저 초대하기 기능

## TODO-List
- [x] 1:1 채팅방 만들기 모달 구현
- [x] 유저 검색 기능
- [ ] 검색한 유저 초대하기 기능
