### ISSUE TITLE
게임 로비 기능 로직 구현

### ISSUE THREAD

**Issue by gkdus2217** [LeHiHo/FastMind#73]
## 목적
게임 로비 기능 로직 구현

## 세부 내용
- 가능한 방 / 모든 방 정렬 기능
- 방 만들기 기능
- 빠른 참여 기능

## TODO-List
- [x] 가능한 방 / 모든 방 정렬 기능
- [x] 방 만들기 기능
- [x] 빠른 참여 기능
- [x] 온라인유저 1:1대화 기능
- [x] 온라인유저 게임 같이하기 기능
- [x] 게임방 채팅 소켓 연결 디버깅
