### ISSUE TITLE
게임방 채팅창 UI 구현

### ISSUE THREAD

**Issue by seacrab808** [LeHiHo/FastMind#88]
## 목적
채팅창 UI

## TODO-List
- [x] 채팅 로직 수정
- [x] 나/다른 사람 메시지 색 차별화
- [x] input 부분 수정
